# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-21 18:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booksAuthors_app', '0002_auto_20180321_1122'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book_author',
            old_name='authors',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='book_author',
            old_name='books',
            new_name='book',
        ),
    ]
