# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-21 18:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksAuthors_app', '0003_auto_20180321_1123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book_author',
            name='author',
        ),
        migrations.RemoveField(
            model_name='book_author',
            name='book',
        ),
        migrations.AddField(
            model_name='author',
            name='books',
            field=models.ManyToManyField(related_name='authors', to='booksAuthors_app.Book'),
        ),
        migrations.DeleteModel(
            name='Book_Author',
        ),
    ]
