# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-21 18:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksAuthors_app', '0004_auto_20180321_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='notes',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
    ]
